version: "3.0"
services: 
  nginx:
    image: custom-nginx:latest
    deploy:
      replicas: 2
    ports: 
      - 8080:80
      - 443:443
    networks: 
      - frontend
    depends_on: 
      - mongo
  mongo:
    image: mongo:latest
    deploy:
    ports:
      - ${MONGO_PORT}:27017
    networks: 
      - backend
    volumes: 
      - ${MONGO_AUTH_SCRIPT}:/docker-entrypoint-initdb.d/mongo-init.js
      - ${MONGO_CONF_FILE}:/etc/mongod.conf.orig
      - ${HOST_MONGO_DB_DATA_DIR}:/data/db
    environment:
      - MONGO_INITDB_DATABASE:${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME:${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD:${MONGO_INITDB_ROOT_PASSWORD}
networks: 
  frontend:
  backend: