version: "3.3"
services: 
  nginx:
    image: custom-nginx:latest
    deploy:
      replicas: 2
    ports: 
      - 8080:80
      - 443:443
    secrets:
      - ssh-key
    networks: 
      - frontend
    depends_on: 
      - mongo
  mongo:
    image: mongo:latest
    deploy:
      replicas: 1
    env_file: .env
    ports:
      - ${MONGO_PORT}:27017
    networks: 
      - backend
    configs:
      - source: INIT_MONGO_SCRIPT
        target: /docker-entrypoint-initdb.d/mongo-init.js

    volumes: 
      # - /Users/surendragalwa/Documents/Learning/Docker/docker-examples/docker-images/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - /Users/surendragalwa/Documents/Learning/Docker/docker-examples/docker-images/mongo/mongod.conf:/etc/mongod.conf.orig
      - /Users/surendragalwa/Documents/Learning/Docker/shared-volume:/data/db
    environment:
      - MONGO_INITDB_DATABASE:all_products
      - MONGO_INITDB_ROOT_USERNAME:root
      - MONGO_INITDB_ROOT_PASSWORD:root
networks: 
  frontend:
  backend:

secrets:
  ssh-key:
    file: ./secret.cert

configs:
  INIT_MONGO_SCRIPT:
    file: /Users/surendragalwa/Documents/Learning/Docker/docker-examples/docker-images/mongo/mongo-init.js