FROM ubuntu:latest

RUN apt-get update && apt-get install -y --no-install-recommends vim \
    && apt-get clean

RUN apt-get update && apt-get install -y --no-install-recommends curl \
    && apt-get clean