version: "3.0"
services: 
  nginx:
    # image: custom-nginx:latest
    build: ../docker-images/nginx/
    ports: 
      - 8080:80
      - 443:443
    networks: 
      - frontend
  mongo:
    image: mongo:latest
    restart: always
    env_file: .env
    ports:
      - ${MONGO_PORT}:27017
    networks: 
      - backend
    volumes: 
      - ${MONGO_AUTH_SCRIPT}:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ${MONGO_CONF_FILE}:/etc/mongod.conf.orig
      - ${HOST_MONGO_DB_DATA_DIR}:/data/db
    # command: mongod --config /etc/mongod.conf.orig
    # command: ["mongod", "-f", "/etc/mongod.conf"]
    environment:
      - MONGO_INITDB_DATABASE:${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME:${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD:${MONGO_INITDB_ROOT_PASSWORD}
networks: 
  frontend:
  backend: