version: "3.0"
services: 
  nginx:
    # image: custom-nginx:latest
    build: ../docker-images/nginx/
    ports: 
      - 8080:80
      - 443:443
    networks: 
      - frontend
  mongo:
    image: mongo:latest
    restart: always
    env_file: .env
    ports:
      - ${MONGO_PORT}:27017
    networks: 
      - backend
    volumes: 
      - ${HOST_MONGO_DB_DATA_DIR}:/data/db
    environment:
      - MONGO_INITDB_DATABASE:${MONGO_INITDB_DATABASE}
      - MONGO_INITDB_ROOT_USERNAME:${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD:${MONGO_INITDB_ROOT_PASSWORD}
networks: 
  frontend:
  backend: